import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {GameDifficultyContextProvider} from "./contexts/DifficultyContext";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Memory Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GameDifficultyContextProvider>{children}</GameDifficultyContextProvider>
      </body>
    </html>
  );
}
